// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpfDev_5wsLURxV5jC-ASEleDQT_REtO4',
    appId: '1:361893336162:web:7c116ddc7d4d3195cb6d3b',
    messagingSenderId: '361893336162',
    projectId: 'news-rss-feed-9f8e5',
    authDomain: 'news-rss-feed-9f8e5.firebaseapp.com',
    storageBucket: 'news-rss-feed-9f8e5.appspot.com',
    measurementId: 'G-9ZVXVPH8N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1yZcR7_pBw0QompmbKr31ez8JA-P-Evg',
    appId: '1:361893336162:android:755e37e8968aa5a1cb6d3b',
    messagingSenderId: '361893336162',
    projectId: 'news-rss-feed-9f8e5',
    storageBucket: 'news-rss-feed-9f8e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1AZpV1msROST1BMf2f9mbegbKRXyukm4',
    appId: '1:361893336162:ios:a65d288016e60308cb6d3b',
    messagingSenderId: '361893336162',
    projectId: 'news-rss-feed-9f8e5',
    storageBucket: 'news-rss-feed-9f8e5.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );
}
